# Assignment 1
Download auto_mpg.txt and store inside 'tabular' folder created inside of 'data' directory. Add this notebook to your python codebase.

The **purpose** of this assignmnet is to become familiar with core Python (*Part 0*), numpy and Pandas basics (*Part 1*), and handling data (*Part 2*).

NAME Theo Dayton
DATE 2/5/23

## Part 0

The goal of Part 0 is to
- Practice problems based on core Python
- Gain better understanding of work-flows controlled by conditional statements

### Resources for python

Here are some of the best resources for Python on the web. 

#### Learning resources

* [Interactive Python](http://interactivepython.org/) An online book that includes embedded live excercises. Fun!
* [Dive Into Python](http://www.diveintopython.net/) An excellent, thorough book.
* [tutorial point](http://www.tutorialspoint.com/python/index.htm) A resource that is useful when you want an explanation of one concept, rather than a whole chapter.


#### Reference resources

Typically, if you have a question about python, you can find an answer by using google. The following sites will usually have the best answer.

* [Official python documentation](https://docs.python.org/3/library/)
* [Quick Reference from Tutorial Point](http://www.tutorialspoint.com/python/python_quick_guide.htm)


**Sample.** Notice the printout below the solution. Notice it is self-documenting, including problem definition and solution (i.e., source code), along with result (i.e., printout).

In [84]:
val = 2
li = [2, 3, 4, 5]
if val in li:
    print('Found value', val, 'in list')
else:
    print('Value', val, 'not found in list')
if 6 in li:
    print('Found value', 6, 'in list')
else:
    print('Value', 6, 'not found in list')
print('List items:', li)


Found value 2 in list
Value 6 not found in list
List items: [2, 3, 4, 5]


**0.1)** 
Describe the 4 core Python containers (note the keyword core, i.e., not numpy arrays or other container types that are included in Python Packages).

a) What are characteristics of each?

The 4 core python containers are lists, tuples, dictionaries and sets.
Lists and tuples are similar, with the main difference being that tuples are unmutable while lists are not
Strings contain single characters
Dictionaries contain key value pairs instead of just values

lists (li=[]), tuples (tu=()), strings (st=""), dictionaries (dic={})-- each are containers with various characteristics.

Lists and tuples can store any type, and can be made up of various different types. Both preserve order (as do strings), with the difference being lists are mutable, while tuples and strings are immutable.

Strings are made up of sequences of characters.

Dictionaries are key-value pairs, where values are accessed via indexing with key. Keys must be unique and are immutable, while values can be of any type and are mutable.

Each container is accessed using square brackets, with indices for tuples, lists, and strings (i.e., ordered) and keys for dictionaries (i.e., unordered).

b) Instantiate each with 0 elements (i.e., empty), and show adding a single element to each.

In [85]:
# instantiate empty containers

emptyTuple = ()

emptyList = []

emptyString = ""

emptyDic = {}


# add single elements

temp = list(emptyTuple)

temp.append('a')
emptyTuple = tuple(temp)

emptyList.append('a')

emptyString += 'a'

emptyDic['a'] = 'b'

c) Provide 1 or more use cases for each.


ANSWER
c) Provide 1 or more use cases for each.

A tuple would be use for a collection of variables which the user will not change. Since tuples are more efficient than lists, a tuple would be the best to use for this case

If the programmer knows that the variables inside will change constantly, then a list would suffice for that case

A dictionary would be used when, for example, one wants to store values that are attached to keys so that they are easier to access. For example, one could use a dictionary when storing information about a single student, such as GPA, or year. When accessing the dictionary using the "gpa" key, it would return the numerical value

Strings are used whenever one wishes to deal with mutable strings, since strings make the accessing and contatenation of individual characters easy.


**0.2)** Write  a program that takes in a positive number (in some variable, say `i`) and computes the sum of all the number
between 0 and that number (inclusive). 

a) Do it using a for loop

In [86]:
i = 10

In [87]:
def sum_forloop(n):
    """
    Function that returns the sum of all numbers in range [0, n].
    :param n: upper limit of summation, which is positive integer greater than 0
    :return: Sum from i=0 to i=n.
    """
    if type(n) is not int or n < 0:
        # check input meets conditions
        return None
    else:
        x = 0
        for num in range(0,n+1):
            x = x + num
        return x
    pass

print('Sum using list using for loop', sum_forloop(i))

Sum using list using for loop 55


b) Do it in one line using the function `sum` and list comprehension.

In [88]:
sum(range(0,i+1))

55

**0.3)** Create a lookup table for your class schedule, with the CRN as keys and the name of class as the value. Loop over the dictionary and print out the CRN and course name (single line per class).

In [89]:
lookupTable = {
    "23167" : "Into Machine Learning",
    "23336" : "Dance Move/Creative Process",
    "23593" : "War & Diplomacy Ancient Wrld.",
    "22320" : "Tennis I",
    "23815" : "Alexander the Great"
}

for CRN,name in lookupTable.items():
    print(CRN,name)

23167 Into Machine Learning
23336 Dance Move/Creative Process
23593 War & Diplomacy Ancient Wrld.
22320 Tennis I
23815 Alexander the Great


**0.4)** Create an empty list. Then, copy the for-loop from previous excercise such that the program prompts you to input the time of the day (as type sting, and using military time would allow for AM and PM to be omitted). These times are to be stored in empty dictionay using the same keys (i.e., CRN->time class starts)

In [90]:
emptyDic2 = {}

for CRN,name in lookupTable.items():
    input_val = input("Enter time of day (military time):")
    emptyDic2[input_val] = name

print(emptyDic2)

{'100': 'Into Machine Learning', '321': 'Dance Move/Creative Process', '42': 'War & Diplomacy Ancient Wrld.', '123': 'Tennis I', '51': 'Alexander the Great'}


**0.5** Write a Python program to convert temperatures to and from Celsius, Fahrenheit.


$$ \frac{c}{5} = \frac{f-32}{9},$$
where $c$ is the temperature in Celsius and $f$ is the temperature in Fahrenheit.

Test code:
60°C is 140 in Fahrenheit
45°F is 7 in Celsius

In [91]:
def fahrenheit2celsius(fahrenheit):
    celsius = (fahrenheit - 32) / 1.8
    return celsius

def celsius2fahrenheit(celsius):
    fahrenheit = (celsius * 1.8) + 32
    return fahrenheit


temp_c = 60
temp_f = 45

temp_c_out = fahrenheit2celsius(temp_f)
temp_f_out = celsius2fahrenheit(temp_c)

print("{} deg. F is {} deg. C".format(temp_f, temp_c_out))
print("{} deg. C is {} deg. F".format(temp_c, temp_f_out))

45 deg. F is 7.222222222222222 deg. C
60 deg. C is 140.0 deg. F


**0.6** Write a Python program to construct the following pattern, using a nested for loop.

O

O X

O X O

O X O X

O X O X O

O X O X

O X O

O X

O

In [92]:
for i in range(5):
    print ("\r")
    for j in range(i):
        if j % 2 == 0:
            print ('O ', end="")
        else:
            print('X ', end="")
    print('\r')

for i in range(5,0,-1):
    print("\r")
    for j in range(i):
        if j % 2 == 0:
            print('O ', end="")
        else:
            print('X ', end="")
    print("\r")





O 

O X 

O X O 

O X O X 

O X O X O 

O X O X 

O X O 

O X 

O 


**0.7** Write a Python program that reads two integers representing a month and day and prints the season for that month and day. Go to the editor
Expected Output:

Input the month (e.g. January, February etc.): july                     
Input the day: 31                                                       
Season is summer

In [93]:
month = input("Input the month (e.g. January, February etc.):")
day = input("Input the day:")
day = int(day)

winterMonths = ("January", "February", "March")
summerMonths = ("July", "August", "September")
springMonths = ("April", "May", "June")


if month in winterMonths:
	season = "winter"
elif month in summerMonths:
	season = "summer"
elif month in springMonths:
	season = "spring"
else:
	season = "autumn"

if (month == "December") and (day > 20):
	season = "winter"
elif (month == "June") and (day > 20):
	season = "summer"
elif (month == "September") and (day > 21):
	season = "autumn"
elif (month == "March") and (day > 19):
	season = "spring"

print("Season is ",season)


Season is  autumn


**0.8** Implement repeats(), as specified in doc-string. Then call on variables a and b below. Print True if repeated, else, print False.

In [110]:
a = [1, 3, 1, 6, 3, 5, 5, 2]
b = [1, 2, 3, 3, 4, 5, 6, 7, 8, 9]

def repeated_val(xs, val=5):

    """ Function to search whether or not 'val' is repeated in sequence.

    :param xs: List of items to search
    :param val: Val being searched (default = 5)
    :return:True if repeated 'val' and neighbors, i.e., [..., 'val', 'val', ...] = True; else, False
    """
    found_before = False
    for x in xs:
        if (x == val) & (found_before == True):
            return True
        elif x == val:
            found_before = True
        else:
            found_before = False
    return False

print("list 'a' repeats 5:", repeated_val(a))
print("list 'a' repeats 6:", repeated_val(a, val=6))
print("list 'b' repeats 5:", repeated_val(b))

list 'a' repeats 5: True
list 'a' repeats 6: False
list 'b' repeats 5: False


## Part 1

The goal in this part is to
- understand basic functionality of numpy and pandas
- learn how to use numpy and pandas to solve common coding tasks
- understand these packages to process real-world data

Import other libraries, such that numpy library is called by with np and pandas with pd

In [95]:
import os
import numpy as np
import pandas as pd

### a) Numpy Basics
*Make sure to leave random seeds in each cell so that the outputs match the expected answer.

### 1)

Create a 10x10 array with random values and find the minimum and maximum values 

In [96]:
np.random.seed(123)

array = np.random.rand(10,10)

print(np.max(array))
print(np.min(array))

0.9953584820340174
0.01612920669501683


### 2)  

Extract the integer part of array Z using 5 different numpy methods

In [97]:
np.random.seed(123)
Z = np.random.uniform(0, 10, 10)

print(Z.astype(int))
print(np.floor_divide(Z,1))
print(np.floor(Z))
print(np.trunc(Z))
print(np.fix(Z))

[6 2 2 5 7 4 9 6 4 3]
[6. 2. 2. 5. 7. 4. 9. 6. 4. 3.]
[6. 2. 2. 5. 7. 4. 9. 6. 4. 3.]
[6. 2. 2. 5. 7. 4. 9. 6. 4. 3.]
[6. 2. 2. 5. 7. 4. 9. 6. 4. 3.]


Create a vector of size 20 with values spanning (0, 1), i.e., 0 and 1 are excluded.

In [98]:
np.random.seed(123)

array = np.random.rand(1,20)
print(array)

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
  0.9807642  0.68482974 0.4809319  0.39211752 0.34317802 0.72904971
  0.43857224 0.0596779  0.39804426 0.73799541 0.18249173 0.17545176
  0.53155137 0.53182759]]


Create a random vector of size 15 and sort it


In [99]:
np.random.seed(123)

array = np.random.rand(1,15)

np.sort(array)

array([[0.0596779 , 0.22685145, 0.28613933, 0.34317802, 0.39211752,
        0.39804426, 0.42310646, 0.43857224, 0.4809319 , 0.55131477,
        0.68482974, 0.69646919, 0.71946897, 0.72904971, 0.9807642 ]])

Consider two random array A anb B, check if they are equal

In [100]:
np.random.seed(123)
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)


np.array_equal(A,B)

False

matplotlib is the plotting library which pandas' plotting functionality is built upon, and it is usually aliased to plt.

%matplotlib inline tells the notebook to show plots inline, instead of creating them in a separate window.

plt.style.use('ggplot') is a style theme that most people find agreeable, based upon the styling of R's ggplot package.

See the documentation <https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html> if you get stuck!

Make an array immutable (read-only)

In [101]:
Z = np.zeros(10)

Z.flags.writeable = False


What if we want to plot multiple things? Pandas allows you to pass in a matplotlib Axis object for plots, and plots will also return an Axis object.

Make a bar plot of monthly revenue with a line plot of monthly advertising spending (numbers in millions)



Create a structured array representing a position (x,y) and a color (r,g,b). Instantiate structured array's values to be all zeros (though same method for other values as well).

In [102]:
array = ([0,0],[15,150,42])

np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

Considering a four dimensions array, how to get sum over the last two axis at once? 

In [103]:
np.random.seed(123)
A = np.random.randint(0, 10, (3, 4, 3, 4))

np.sum(A,axis=(2,3))

array([[40, 37, 56, 43],
       [61, 44, 54, 70],
       [48, 53, 64, 71]])

Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [104]:
np.random.seed(123)
w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
print(I.shape)

image2 = np.reshape(I, (-1,3))

unique_rows, counts = np.unique(image2, return_counts=True, axis=0)

print(unique_rows.shape[0])

(16, 16, 3)
8


How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [105]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)

unique_indices = np.unique(I)

accumulate_elements = np.zeros_like(F)

for i, index in enumerate(unique_indices):
    accumulate_elements[index] += X[i] * counts[i]

F += accumulate_elements

print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]
[  0.  37.   0.  70.  95.   0.   0.   0.   0. 151.]


How to read the following file?

In [106]:
fpath = os.path.join("data", "tabular", "missing.dat")

array_from_file = np.fromfile(fpath,dtype="dt")

TypeError: data type 'dt' not understood


Convert a vector of ints into a matrix binary representation

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)

print(B[:,::-1])

Given a two dimensional array, how to extract unique rows?

In [ ]:
Z = np.random.randint(0, 2, (6, 3))
print(Z)

rows = np.unique(Z, axis=0)
print(rows)

## Pandas

Made-up data representing animals and trips to vet

In [ ]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


Create a DataFrame df from this dictionary data which has the index labels.

In [ ]:
df = pd.DataFrame(data, index=labels)

print(df)

Display a summary of the basic information about this DataFrame and its data.

In [ ]:
df.describe()

Return the first 3 rows of the DataFrame df.

In [ ]:
df.head(3)

Select just the 'animal' and 'age' columns from the DataFrame df.

In [ ]:
columns = df[["animal", "age"]]

Change the age in row 'f' to 1.5.

In [ ]:
df.loc["f", "age"] = 1.5

Calculate the mean age for each different animal in df.

In [ ]:
df.mean()

 In the 'animal' column, change the 'snake' entries to 'python'.

In [ ]:
df.loc[(df['animal'] == "snake"), 'animal'] = 'python'


For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (hint: use a pivot table).

In [ ]:
table = pd.pivot_table(df, index=['animal'],
                    columns=['visits'])
print(table)

Given a DataFrame, subtract the row mean from each element in the row?

In [ ]:
# a 5x3 frame of float values
df_floats = pd.DataFrame(np.random.random(size=(5, 3)))


df_floats = df_floats.sub(df_floats.mean(axis=1), axis=0)

### Series and Datetimeindex

Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series s.

In [ ]:
start = '2015-01-01'
end = '2015-12-31'
business_days = pd.bdate_range(start, end)

s = pd.Series(np.random.randn(len(business_days)), index=business_days)


Find the sum of the values in s for every Wednesday.

In [ ]:
wednesdays = s.index.dayofweek == 2
sum_of_wednesdays = s[wednesdays].sum()

For each calendar month in s, find the mean of values.

In [ ]:
monthly_mean = s.resample('M').mean()

For each group of four consecutive calendar months in s, find the date on which the highest value occurred.

In [ ]:
monthly_max = monthly_mean.groupby((monthly_mean.index.month - 1) // 4).idxmax()

### Cleaning Data

The DataFrame to use in the following puzzles:

In [ ]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

df.head()

 Some values in the the FlightNumber column are missing. These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Fill in these missing numbers and make the column an integer column (instead of a float column).

In [ ]:
df.at[1,'FlightNumber'] = 10055
df.at[3,'FlightNumber'] = 10075
df['FlightNumber'] = df['FlightNumber'].astype(int)
df.head()

The From_To column would be better as two separate columns! Split each string on the underscore delimiter _ to give a new temporary DataFrame with the correct values. Assign the correct column names to this temporary DataFrame.

In [ ]:
df2 = pd.DataFrame()
df2[['From', 'To']] = df['From_To'].str.split('_', expand=True)
print(df2)

Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [ ]:
df2 = df2.apply(lambda x: x.str.capitalize())

Delete the From_To column from df and attach the temporary DataFrame from the previous questions.

In [ ]:
df = df.drop('From_To', axis=1)
df = pd.concat([df2, df], axis=1, join='inner')

df.head()

### Plotting
Pandas is integrated with the plotting library matplotlib, and makes plotting DataFrames very user-friendly! Plotting in a notebook environment usually makes use of the following boilerplate:

matplotlib is the plotting library which pandas' plotting functionality is built upon, and it is usually aliased to plt.

%matplotlib inline tells the notebook to show plots inline, instead of creating them in a separate window.

plt.style.use('ggplot') is a style theme that most people find agreeable, based upon the styling of R's ggplot package.

See the documentation <https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html> if you get stuck!

In [108]:
import matplotlib.pyplot as plt
%matplotlib
plt.style.use('ggplot')

Using matplotlib backend: <object object at 0x000001EFA20657D0>


In [ ]:
df = pd.DataFrame({"xs":[1,5,2,8,1], "ys":[4,2,1,9,6]})

### 1.31)
For starters, make a scatter plot of this random data, but use black X's instead of the default markers. Add title "Scatter Plot" to the plot. Use df from previous cell.

*NOTE: Don't forget to add [any] title and axes labels*

In [109]:
import matplotlib.pyplot as plt
%matplotlib
plt.style.use('ggplot')

plt.scatter(df['xs'],df['ys'], marker='x', color='black')

plt.title("Scatter Plot")

plt.xlabel("X Axis")

plt.ylabel("Y Axis")

plt.show()

NameError: name 'df' is not defined

Columns in your DataFrame can also be used to modify colors and sizes. Bill has been keeping track of his performance at work over time, as well as how good he was feeling that day, and whether he had a cup of coffee in the morning. Make a plot which incorporates all four features of this DataFrame.

(Hint: If you're having trouble seeing the plot, try multiplying the Series which you choose to represent size by 10 or more)

In [ ]:
import pandas as pd
df2 = pd.DataFrame({"productivity":[5,2,3,1,4,5,6,7,8,3,4,8,9],
                   "hours_in"    :[1,9,6,5,3,9,2,9,1,7,4,2,2],
                   "happiness"   :[2,1,3,2,3,1,2,3,1,2,2,1,3],
                   "caffienated" :[0,0,1,1,0,0,0,0,1,1,0,1,0]})

dates = pd.date_range(start='2023-01-01', periods=13, freq='D')
df2['Date'] = dates

# Plot the dataframe
fig, ax = plt.subplots()
ax.scatter(np.arange(13), df2['productivity'], color='red', marker='x', label='productivity')
ax.scatter(np.arange(13), df2['hours_in'], color='blue', marker='x', label='hours_in')
ax.scatter(np.arange(13), df2['happiness'], color='green', marker='x', label='happiness')
ax.scatter(np.arange(13), df2['caffienated'], color='purple', marker='x', label='caffienated')

# Add title, x and y labels
ax.set_title('Scatter Plot')
ax.set_xlabel('Day')
ax.set_ylabel('Values')

# Add a legend
ax.legend()

markers = ['X' if coffee else 'o' for coffee in df['caffienated']]


# Show the plot
ax.show()

### 1.33)
What if we want to plot multiple things? Pandas allows you to pass in a matplotlib Axis object for plots, and plots will also return an Axis object.

Make a bar plot of monthly revenue with a line plot of monthly advertising spending (numbers in millions)
- Two plots should be in one figure
- Make sure that the y-axis scales of 2 plots are different
- Be sure to include legend

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


df_to_plot = pd.DataFrame({"revenue":[57,68,63,71,72,90,80,62,59,51,47,52],
                   "advertising":[2.1,1.9,2.7,3.0,3.6,3.2,2.7,2.4,1.8,1.6,1.3,1.9],
                   "month":range(12)
                  })

# Create a bar plot of monthly revenue
fig2, ax1 = plt.subplots()
ax1.bar(df_to_plot['month'], df_to_plot['revenue'], color='blue', label='Revenue')
ax1.set_xlabel('Month')
ax1.set_ylabel('Revenue')
ax1.set_ylim(0, 35)
ax1.legend(loc="upper left")

# Create a line plot of monthly advertising spending
ax2 = ax1.twinx()
ax2.plot(df_to_plot['month'], df_to_plot['advertising'], color='red', label='Ads')
ax2.set_ylabel('Ads')
ax2.set_ylim(0, 20)
ax2.legend(loc="upper right")

# Show the plot
plt.show()

### 1.33)
What if we want to put the x-axis in a different scale? Create two line plots with xs as x-axis and ys as y-axis. First plot uses log scaling on x-axis, and the second plot uses default scaling on x-axis. 

In [ ]:
df3 = pd.DataFrame({"xs":np.logspace(-2, 2, base=10, num=12),
                   "ys":range(12)
                  })

fig3, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))
ax1.plot(df3['xs'], df3['ys'])
ax1.set_title("Log Scaling on X-axis")
ax1.set_xscale("log")

# Second plot with default scaling on x-axis
ax2.plot(df3['xs'], df3['ys'])
ax2.set_title("Default Scaling on X-axis")

plt.tight_layout()
plt.show()

##Matrix Manipulations
Lets first create a matrix and perform some manipulations of it.

Using numpy's matrix data structure, define the following matricies:

$$A=\left[ \begin{array}{ccc} 3 & 5 & 9 \\ 3 & 3 & 4 \\ 5 & 9 & 17 \end{array} \right]$$

$$B=\left[ \begin{array}{c} 2 \\ 1 \\ 4 \end{array} \right]$$

After this solve the matrix equation:
$$Ax = B$$

In [ ]:
A = np.array([[3, 5, 9], [3, 3, 4], [5, 9, 17]])

B = np.matrix([[2], [1], [4]])




Now write three functions for matrix multiply $C=AB$ in each of the following styles:

1. By using nested for loops to impliment the naive algorithm ($C_{ij}=\sum_{k=0}^{m-1}A_{ik}B_{kj}$)
2. Using numpy's built in martrix multiplication  

Both methods should have the same answer

In [ ]:
rows_A, cols_A = A.shape
rows_B, cols_B = B.shape

C = np.zeros((rows_A, cols_B))

for i in range(rows_A):
    for j in range(cols_B):
        dot_product = 0
        for k in range(cols_A):
            dot_product += A[i,k] * B[k,j]
        C[i,j] = dot_product
print(C)

In [ ]:
C = np.dot(A, B)
print(C)

## Part 2
Getting used to the data

In [ ]:
# Reads text file and uses '|' as separator
auto = pd.read_table('data/tabular/auto_mpg.txt', sep='|')
auto.head()

Answer the following questions about the data:

a) What is the shape of the data?

In [ ]:
auto.shape

b) How many rows and columns are there?

In [ ]:
print(392)
print(9)

c) What variables are available?

In [ ]:
auto.columns

d) What are the ranges for the values in each numeric column?

In [ ]:
def get_range(name_col):
    result = auto[name_col].max() - auto[name_col].min()
    return result

for name in auto.columns:
    if name != "car_name":
        print(get_range(name))

e) What is the average value for each column?  Does that differ significantly
  from the median?

In [ ]:
for name in auto.columns:
    if name != "car_name":
        print(auto[name].mean())

for name in auto.columns:
    if name != "car_name":
        print(auto[name].median())

Answer the following questions about the data:

a) Which 5 cars get the best gas mileage?

In [ ]:
top_5 = auto['mpg'].nlargest(5)

print(auto.loc[top_5.index, 'car_name'])

b) Which 5 cars with more than 4 cylinders get the best gas mileage?

In [ ]:
top_5_cond = auto.loc[auto['cylinders'] > 4].nlargest(5, 'mpg')

print(auto.loc[top_5_cond.index, 'car_name'])

c) Which 5 cars get the worst gas mileage?

In [ ]:
bot_5 = auto['mpg'].nsmallest(5)

print(auto.loc[bot_5.index, 'car_name'])

d) Which 5 cars with 4 or fewer cylinders get the worst gas mileage?

In [ ]:
bot_5_cond = auto.loc[auto['cylinders'] < 5].nsmallest(5, 'mpg')

print(auto.loc[bot_5_cond.index, 'car_name'])

Part 4
Use groupby and aggregations to explore the relationships 
between mpg and the other variables.  Which variables seem to have the greatest
effect on mpg?
Some examples of things you might want to look at are:
- What is the mean mpg for cars for each number of cylindres (i.e. 3 cylinders,
  4 cylinders, 5 cylinders, etc)?
- Did mpg rise or fall over the years contained in this dataset?
- What is the mpg for the group of lighter cars vs the group of heaver cars?
Note: Be creative in the ways in which you divide up the data.  You are trying
to create segments of the data using logical filters and comparing the mpg
for each segment of the data.

In [ ]:
grouped = auto.groupby('cylinders').mean()['mpg']

print(grouped)

grouped2 = auto.groupby('model_year').mean()['mpg']

print(grouped2)

mpg_by_weight = auto.groupby(auto['weight'] // auto['weight'].mean()).mean()['mpg']


print(mpg_by_weight)

Let's now look how MPG has changed over time, while also considering
how specific groups have changed-- look at low, mid, and high power
cars based upon their horsepower and see how these groups have changed over time.

In his data, he called the original dataset 'auto'.

**Now to look at how efficency has changed over time based on power and weight classes, two things that we know play a large role in gas mileage.  First, we create a table of efficeincy by power class and year.**

In [ ]:
import matplotlib.pyplot as plt
auto['horsepower_group'] = auto['horsepower'].apply(lambda x: 'high' if x > 150 else ('medium' if 150 >= x > 100 else 'low'))

auto.head()

grouped = auto.groupby('horsepower_group')


for name, group in grouped:
    plt.plot(group["model_year"], group["mpg"], label=str(name) + " horsepower")

# Add a legend to the plot
plt.legend()

# Label the x-axis
plt.xlabel("Model Year")

# Label the y-axis
plt.ylabel("MPG")

# Show the plot
plt.show()